package Main.syntaxAnalysis;

import Main.AST.ComandoAtribuiçãoNode;
import Main.AST.ComandoCompostoNode;
import Main.AST.ComandoCondicionalNode;
import Main.AST.ComandoIterativoNode;
import Main.AST.ComandoNode;
import Main.AST.CorpoNode;
import Main.AST.DeclaraçãoDeVariávelNode;
import Main.AST.DeclaraçãoNode;
import Main.AST.DeclaraçãoSequencialNode;
import Main.AST.ExpressãoNode;
import Main.AST.ExpressãoSimplesNode;
import Main.AST.FatorNode;
import Main.AST.ListaDeComandosNode;
import Main.AST.ListaDeIdsNode;
import Main.AST.LiteralNode;
import Main.AST.Node;
import Main.AST.OperadorNode;
import Main.AST.ProgramaNode;
import Main.AST.SeletorNode;
import Main.AST.SequênciaFatoresNode;
import Main.AST.SequênciaTermosNode;
import Main.AST.TermoNode;
import Main.AST.TipoAgregadoNode;
import Main.AST.TipoNode;
import Main.AST.TipoSimplesNode;
import Main.AST.VariávelNode;
import Main.lexicalAnalysis.Token;

public interface Visitor {
	public void visitComandoAtribuição(ComandoAtribuiçãoNode CA);
	public void visitComandoComposto(ComandoCompostoNode CC);
	public void visitComandoCondicional(ComandoCondicionalNode CC);
	public void visitComandoIterativo(ComandoIterativoNode CC);
	public void visitComando(ComandoNode C);
	public void visitCorpo(CorpoNode C);
	public void visitDeclaraçãoDeVariável(DeclaraçãoDeVariávelNode D);
	public void visitDeclaração(DeclaraçãoNode D);
	public void visitDeclaraçãoSequencial(DeclaraçãoSequencialNode D);
	public void visitExpressão(ExpressãoNode E);
	public void visitExpressãoSimples(ExpressãoSimplesNode ES);
	public void visitFator(FatorNode F);
	public void visitListaDeComandos(ListaDeComandosNode LC);
	public void visitListaDeIds(ListaDeIdsNode LI);
	public void visitLiteral(LiteralNode L);
	public void visitNode(Node N);
	public void visitOperador(OperadorNode O);
	public void visitPrograma(ProgramaNode P);
	public void visitSeletor(SeletorNode S);
	public void visitSequênciaFatores(SequênciaFatoresNode SF);
	public void visitSequênciaTermos(SequênciaTermosNode ST);
	public void visitTermo(TermoNode T);
	public void visitTipoAgregado(TipoAgregadoNode TA);
	public void visitTipo(TipoNode T);
	public void visitTipoSimples(TipoSimplesNode TS);
	public void visitToken(Token T);
	public void visitVariável(VariávelNode V);
}
